pipeline {   
    agent any 
    stages {
        stage('Build') {
            steps {
			    sh 'docker run --rm --volume="/home/app/jenkins/workspace/blog:/srv/jekyll" --volume="/home/app/jekyll/bundle:/usr/local/bundle"  -i w0sephiroth/myjekyll:3.8 jekyll build'
            }
        }
        stage('Deploy') { 
            steps {
                sh './jenkins/scripts/deploy.sh' 
            }
        }
    }
}