pipeline {    
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'myjekyll3.8'
                    args '-v $PWDsrvjekyll -v homeappjekyllbundleusrlocalbundle'
                }
            }
            steps {
                sh 'jekyll build'
            }
        }
        stage('Deploy') { 
            steps {
                sh './jenkins/scripts/deploy.sh' 
            }
        }
    }
}